#!/usr/bin/env python
# coding: utf-8

# In[9]:


from parse_csv_data import parse
from base_probability import get_probability_hometeam_wins
from base_probability import get_probability_external_team_wins


if __name__ == '__main__':
    #csv file containing the different matches
    data = "../example_data/BuliDaten.csv"

    #load the csv matches
    matches = parse(data)

    #output the matches
    for match in matches:
        print(match)

    print("")
    print("Hamburger SV wins vs Borussia Dortmund: " + str(get_probability_hometeam_wins(matches, "Hamburger SV" ,"Borussia Dortmund")))
    print("Borussia Dortmund wins vs Hamburger SV: " + str(get_probability_external_team_wins(matches, "Hamburger SV" ,"Borussia Dortmund")))

    print("")
    print("FC Bayern wins vs Borussia Dortmund: " + str(get_probability_hometeam_wins(matches, "FC Bayern" ,"Borussia Dortmund")))
    print("Borussia Dortmund wins vs FC Bayern: " + str(get_probability_external_team_wins(matches, "FC Bayern" ,"Borussia Dortmund")))

